export const AJOUTER_DANS_PANIER = "AJOUTER_DANS_PANIER"
export const SUPPRIMER_DU_PANIER = "SUPPRIMER_DU_PANIER"
export const PLUS_DANS_PANIER = "PLUS_DANS_PANIER"
export const MOINS_DANS_PANIER = "MOINS_DANS_PANIER"